uhell /usr/bin/fish

include ./themes/mocha.conf

font_family Go Mono

font_size 13.0

disable_ligatures never

mouse_hide_wait -1

cursor_shape block

cursor_blink_interval -1

hide_window_decorations yes

clipboard_control write-clipboard write-primary no-append

term xterm-256color
